name: Auto-Merge Dependency Bot PRs

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    name: auto-merge
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'renovate[bot]' || github.actor == 'dependabot[bot]' }}
    steps:
      - name: Run action
        uses: invi5H/dependabot-automerge@main
